'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { spawnSync } = require('node:child_process');
const { DatabaseSync } = require('node:sqlite');
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'hipkop-migration-'));
process.env.HIPKOP_DB_PATH = path.join(dir, 'original.sqlite');
process.env.HIPKOP_MEDIA_DIR = path.join(dir, 'original-media');
const repo = require('../src/repo'), { db, run } = require('../src/db');
const migration = require('../scripts/migrate-data');
const bundle = path.join(dir, 'private-bundle');
const artwork = 'a'.repeat(40) + '.jpg';
test.after(() => { db.close(); fs.rmSync(dir, { recursive: true, force: true }); });
test('migration: exports consistent WAL snapshot, portable artwork, real posts and no active sessions', () => {
  repo.createPost({ title: '保留原帖', body: '真正的数据迁移', author: '原作者' });
  fs.writeFileSync(path.join(process.env.HIPKOP_MEDIA_DIR, artwork), Buffer.from('test-image-bytes'));
  repo.beginCover('https://is1-ssl.mzstatic.com/test.jpg');
  repo.completeCover('https://is1-ssl.mzstatic.com/test.jpg', { localPath: `C:\\old-computer\\media\\${artwork}`, contentType: 'image/jpeg', bytes: 16 });
  run("INSERT INTO users VALUES('u','testuser','测试','hash',?)", [new Date().toISOString()]);
  run("INSERT INTO sessions VALUES('token','u','csrf',?)", [Date.now() + 60000]);
  const manifest = migration.exportData(bundle);
  assert.equal(manifest.counts.community_posts, 1);
  assert.equal(manifest.files.length, 2);
  migration.verifyBundle(bundle);
  const copy = new DatabaseSync(path.join(bundle, 'hipkop.sqlite'), { readOnly: true });
  assert.equal(copy.prepare('SELECT COUNT(*) AS n FROM sessions').get().n, 0);
  assert.equal(copy.prepare('SELECT local_path FROM cover_cache').get().local_path, artwork);
  copy.close();
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM sessions').get().n, 1, 'source untouched');
});
test('migration: restores to another directory, validates checksums and refuses overwrite', () => {
  const target = path.join(dir, 'restored.sqlite'), media = path.join(dir, 'restored-media');
  const command = () => spawnSync(process.execPath, ['scripts/migrate-data.js','restore',bundle], { cwd: path.resolve(__dirname, '..'), env: { ...process.env, HIPKOP_DB_PATH: target, HIPKOP_MEDIA_DIR: media }, encoding: 'utf8' });
  const restored = command();
  assert.equal(restored.status, 0, restored.stderr);
  assert.ok(fs.existsSync(path.join(media, artwork)));
  const copy = new DatabaseSync(target, { readOnly: true });
  assert.equal(copy.prepare('SELECT author FROM community_posts').get().author, '原作者'); copy.close();
  assert.notEqual(command().status, 0, 'existing database never overwritten');
  const file = path.join(bundle, 'media', artwork);
  fs.appendFileSync(file, 'corrupt');
  assert.throws(() => migration.verifyBundle(bundle), /checksum mismatch/);
});
